// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ArtLovers.Model.Models;

public partial class Arte
{
    public int IdArte { get; set; }

    public string Arte1 { get; set; }

    public DateTime Data { get; set; }

    public virtual ICollection<Pessoa> Pessoa { get; set; } = new List<Pessoa>();

    public virtual ICollection<Publicacao> Publicacao { get; set; } = new List<Publicacao>();
}