// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ArtLovers.Model.Models;

public partial class Cartao
{
    public int IdCartao { get; set; }

    public string NumeroCartao { get; set; }

    public int? MesVencimento { get; set; }

    public int? AnoVencimento { get; set; }

    public string TipoCartao { get; set; }

    public DateTime Data { get; set; }

    public virtual ICollection<Pessoa> Pessoa { get; set; } = new List<Pessoa>();
}