// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ArtLovers.Model.Models;

public partial class Comunidade
{
    public int IdComunidade { get; set; }

    public string Comunidade1 { get; set; }

    public virtual ICollection<Publicacao> Publicacao { get; set; } = new List<Publicacao>();
}