// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ArtLovers.Model.Models;

public partial class Pessoa
{
    public int IdPessoa { get; set; }

    public int? IdArte { get; set; }

    public int? IdCartao { get; set; }

    public string Nome { get; set; }

    public string UserName { get; set; }

    public string Senha { get; set; }

    public string Email { get; set; }

    public bool Administrador { get; set; }

    public DateTime Data { get; set; }

    public int? IdPublicacao { get; set; }

    public virtual Arte IdArteNavigation { get; set; }

    public virtual Cartao IdCartaoNavigation { get; set; }

    public virtual Publicacao IdPublicacaoNavigation { get; set; }

    public virtual ICollection<Publicacao> Publicacao { get; set; } = new List<Publicacao>();
}