// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ArtLovers.Model.Models;

public partial class Publicacao
{
    public int IdPublicacao { get; set; }

    public int IdPessoa { get; set; }

    public int IdArte { get; set; }

    public int IdComentario { get; set; }

    public int? IdComunidade { get; set; }

    public int IdTag { get; set; }

    public DateTime Data { get; set; }

    public virtual Arte IdArteNavigation { get; set; }

    public virtual Comentario IdComentarioNavigation { get; set; }

    public virtual Comunidade IdComunidadeNavigation { get; set; }

    public virtual Pessoa IdPessoaNavigation { get; set; }

    public virtual Tag IdTagNavigation { get; set; }

    public virtual ICollection<Pessoa> Pessoa { get; set; } = new List<Pessoa>();
}